### ISSUE TITLE
Cmake errors

### ISSUE THREAD

**Issue by gmsotavio** [gitahead/gitahead#139]
Hi, I have been facing the following cmake errors on Linux Debian 9 (stretch) as output for the following command

`cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../..`

```
-- 
-- The following features have been enabled:

 * diffie-hellman-group-exchange-sha1 , "new" diffie-hellman-group-exchange-sha1 method

-- The following OPTIONAL packages have been found:

 * Git
 * OpenSSL

-- The following REQUIRED packages have been found:

 * Qt5Concurrent
 * Qt5Core
 * Qt5Gui
 * Qt5Network
 * Qt5PrintSupport
 * Qt5Widgets
 * Qt5Test
 * Qt5

-- The following features have been disabled:

 * Shared library , creating libssh2 as a shared library (.so/.dll)
 * Compression , using zlib for compression
 * "none" cipher
 * "none" MAC
 * Logging , Logging of execution with debug trace

-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
--   Resolved libraries: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Found mbedTLS:
--   version 2.13.1
--   TLS: /usr/local/lib/libmbedtls.a
--   X509: /usr/local/lib/libmbedx509.a
--   Crypto: /usr/local/lib/libmbedcrypto.a
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT-FALLTHROUGH=1_SUPPORTED
-- Performing Test IS_WIMPLICIT-FALLTHROUGH=1_SUPPORTED - Failed
-- Enabled features:
 * diffie-hellman-group-exchange-sha1 , "new" diffie-hellman-group-exchange-sha1 method
 * threadsafe , threadsafe support
 * cURL , cURL for HTTP proxy support
 * HTTPS , using OpenSSL
 * SHA , using CollisionDetection
 * http-parser , http-parser support (bundled)
 * zlib , using system zlib
 * SSH , SSH transport support

-- Disabled features:
 * Shared library , creating libssh2 as a shared library (.so/.dll)
 * Compression , using zlib for compression
 * "none" cipher
 * "none" MAC
 * Logging , Logging of execution with debug trace
 * debugpool , debug pool allocator
 * tracing , tracing support
 * SPNEGO , SPNEGO authentication support
 * iconv , iconv encoding conversion support

CMake Error at pack/CMakeLists.txt:34 (get_target_property):
  get_target_property() called with non-existent target "Qt5::QJpegPlugin".


CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:34 (get_target_property):
  get_target_property() called with non-existent target
  "Qt5::QXcbIntegrationPlugin".


CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments


-- Configuring incomplete, errors occurred!
See also "/home/otaviogomes/tmp/gitahead/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/otaviogomes/tmp/gitahead/build/release/CMakeFiles/CMakeError.log".


```
Files
- [CMakeError.log](https://github.com/gitahead/gitahead/files/2717118/CMakeError.log)
- [CMakeOutput.log](https://github.com/gitahead/gitahead/files/2717119/CMakeOutput.log)

Some idea ?

**Comment by hackhaslam** [comment]
Qt 5.7 in Debian 9 is too old. I recommend installing 5.12 if possible. I believe that the hard requirement is Qt 5.9. I'll add the requirement to the CMake file and the README.

**Comment by gmsotavio** [comment]
I've tried with Ubuntu and Qt 5.9; I got the same output. I'm unable to solve this. I ended up with the binary package. No way to compile from source.

**Comment by hackhaslam** [comment]
Perhaps the JPEG plugin isn't found because JPEG support is built into the system Qt statically on Debian. I can investigate further when I have a moment.

It should still be possible to build GitAhead by downloading the binary distribution of Qt or building it from source.

**Comment by scottdensmore** [comment]
I am having the same problem on Ubuntu 18.10 cosmic. The following is the output of running CMake in CLion (running from the command line fails too). 

I installed `qt5-default` form `apt`.  I am not sure what plug-in I need for the jpeg.

```- The C compiler identification is Clang 7.0.1
-- The CXX compiler identification is Clang 7.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.20.1") 
CMake Warning (dev) at dep/libssh2/libssh2/CMakeLists.txt:52 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_SHARED_LIBS'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenSSL: /home/scottdensmore/Dev/gitahead/dep/openssl/openssl/libcrypto.so (found version "1.1.1a")  
-- Looking for EVP_aes_128_ctr
-- Looking for EVP_aes_128_ctr - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/uio.h
-- Looking for include file sys/uio.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file sys/un.h
-- Looking for include file sys/un.h - found
-- Looking for include file windows.h
-- Looking for include file windows.h - not found
-- Looking for include file ws2tcpip.h
-- Looking for include file ws2tcpip.h - not found
-- Looking for include file winsock2.h
-- Looking for include file winsock2.h - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for memset_s
-- Looking for memset_s - not found
-- Looking for poll
-- Looking for poll - found
-- Looking for socket
-- Looking for socket - found
-- Looking for select
-- Looking for select - found
-- Looking for inet_addr
-- Looking for inet_addr - found
-- Performing Test HAVE_O_NONBLOCK
-- Performing Test HAVE_O_NONBLOCK - Success
-- The following features have been enabled:

 * diffie-hellman-group-exchange-sha1, "new" diffie-hellman-group-exchange-sha1 method
 * Logging, Logging of execution with debug trace

-- The following OPTIONAL packages have been found:

 * Git
 * OpenSSL

-- The following REQUIRED packages have been found:

 * Qt5Concurrent
 * Qt5Core
 * Qt5Gui
 * Qt5Network
 * Qt5PrintSupport
 * Qt5Widgets
 * Qt5Test
 * Qt5 (required version >= 5.9)

-- The following features have been disabled:

 * Shared library, creating libssh2 as a shared library (.so/.dll)
 * Compression, using zlib for compression
 * "none" cipher
 * "none" MAC

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Success
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Success
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED - Success
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED - Success
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED - Success
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED - Success
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED - Success
-- Performing Test IS_WFORMAT_SUPPORTED
-- Performing Test IS_WFORMAT_SUPPORTED - Success
-- Performing Test IS_WFORMAT_SECURITY_SUPPORTED
-- Performing Test IS_WFORMAT_SECURITY_SUPPORTED - Success
-- Performing Test IS_WINT_CONVERSION_SUPPORTED
-- Performing Test IS_WINT_CONVERSION_SUPPORTED - Success
-- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED
-- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED - Success
-- Looking for regcomp_l
-- Looking for regcomp_l - not found
-- Looking for futimens
-- Looking for futimens - found
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY) 
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED - Failed
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Looking for libssh2_userauth_publickey_frommemory in libssh2
-- Looking for libssh2_userauth_publickey_frommemory in libssh2 - not found
-- Enabled features:
 * diffie-hellman-group-exchange-sha1, "new" diffie-hellman-group-exchange-sha1 method
 * Logging, Logging of execution with debug trace
 * threadsafe, threadsafe support
 * HTTPS, using OpenSSL
 * SHA, using CollisionDetection
 * http-parser, http-parser support (bundled)
 * zlib, using system zlib
 * SSH, SSH transport support

-- Disabled features:
 * Shared library, creating libssh2 as a shared library (.so/.dll)
 * Compression, using zlib for compression
 * "none" cipher
 * "none" MAC
 * debugpool, debug pool allocator
 * tracing, tracing support
 * SPNEGO, SPNEGO authentication support
 * iconv, iconv encoding conversion support

CMake Deprecation Warning at dep/cmark/cmark/CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Performing Test HAVE_FLAG_ADDRESS_SANITIZER
-- Performing Test HAVE_FLAG_ADDRESS_SANITIZER - Failed
-- Performing Test HAVE_FLAG_SANITIZE_ADDRESS
-- Performing Test HAVE_FLAG_SANITIZE_ADDRESS - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.6
-- Checking for module 'gnome-keyring-1'
--   Found gnome-keyring-1, version 3.12.0
CMake Error at pack/CMakeLists.txt:34 (get_target_property):
  get_target_property() called with non-existent target "Qt5::QJpegPlugin".


CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:34 (get_target_property):
  get_target_property() called with non-existent target
  "Qt5::QXcbIntegrationPlugin".


CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
  get_filename_component called with incorrect number of arguments


CMake Error at pack/CMakeLists.txt:37 (get_filename_component):
  get_filename_component called with incorrect number of arguments
```

**Comment by ootwch** [comment]
Same here.
Note that the plugin seems to exist as 
`/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so`, 
so perhaps this is just a path issue?

**Comment by alexisfrjp** [comment]
Same as you guys:
```
CMake Error at pack/CMakeLists.txt:34 (get_target_property):
  get_target_property() called with non-existent target "Qt5::QJpegPlugin".
```

Using a Docker container using Ubuntu 19.04 (Disco) and Qt**5.12**.2: https://packages.ubuntu.com/disco/qt5-default

**Comment by likeawindrammer** [comment]
Same issue on Ubuntu 18.04 with QT5.9.

**Comment by likeawindrammer** [comment]
Okay, just about everything thought to be a given is wrong.

First this is how you actually build gitahead (or what worked for me at atleast):
1. Right-clic CMakeLists.txt from the root of the project and open it with Qt Creator.
2. Wait until Qt Creator finish configuring the project
3. Compile with Qt 5.12 or up (that's right, Qt 5.9 definitely won't work because it fails to build)
4. Wait for a while until it finishes compiling and then you will have a binary you can run from Qt Creator

Second, as you can see building from the command line on Linux as the ReadMe says just won't work, even if you have Qt 5.12 as someone mention on https://github.com/gitahead/gitahead/issues/219
While building with Qt 5.12 or up as installed by the Qt Maintenance Tool and compiled with Qt Creator does work.
Configuring the project on Qt Creator with Qt 5.9 from the ubuntu repository will fail with the exact same issue as described in this issue.

Third, Qt 5.9 isn't the minimum anymore even if you install it with Qt Maintenance Tool and build it with Qt Creator because even though Qt Creator will succed configuring the project. It will fail at compile time with this error:
```
/home/windrammer/dev/gitahead/src/editor/PlatQt.cpp:511: error: ‘screenAt’ is not a member of ‘QApplication’
   if (QScreen *screen = QApplication::screenAt(QPoint(ox, oy))) {
                                       ^~~~~~~~
```

**Comment by Mailaender** [comment]
I compiled with Qt 5.12 and it still errors:

```
[   21s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   21s]   get_target_property() called with non-existent target "Qt5::QJpegPlugin".
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   21s]   get_target_property() called with non-existent target
[   21s]   "Qt5::QXcbIntegrationPlugin".
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:33 (get_target_property):
[   21s]   get_target_property() called with non-existent target
[   21s]   "Qt5::QComposePlatformInputContextPlugin".
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:34 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:35 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
[   21s] 
[   21s] 
[   21s] CMake Error at pack/CMakeLists.txt:36 (get_filename_component):
[   21s]   get_filename_component called with incorrect number of arguments
```

Looks like the cmake macros are wrong on multiple occasions.

**Comment by hackhaslam** [comment]
@Mailaender Did you build with the system Qt or download binaries from qt.io?

**Comment by Mailaender** [comment]
@openSUSE system Qt. https://build.opensuse.org/package/show/home:Mailaender:branches:devel:tools:scm/gitahead

**Comment by hackhaslam** [comment]
@Mailaender you will likely have to download Qt from qt.io and build against it instead.

**Comment by Mailaender** [comment]
That is not acceptable for most Linux distributions. Everything has to be unbundled and built from source.

**Comment by LeSpocky** [comment]
> That is not acceptable for most Linux distributions. Everything has to be unbundled and built from source.

+1, FWIW I tried building master on Debian GNU/Linux 10 (buster) yesterday and that failed, too.

**Comment by hackhaslam** [comment]
I believe this should be fixed now.
